name: taho_story
description: "A modern Flutter mobile ordering app for Taho Story"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: HarmonyOS Sans
      fonts:
        - asset: fonts/HarmonyOS_Sans_Thin.ttf
          weight: 100
        - asset: fonts/HarmonyOS_Sans_Thin_Italic.ttf
          weight: 100
          style: italic
        - asset: fonts/HarmonyOS_Sans_Light.ttf
          weight: 300
        - asset: fonts/HarmonyOS_Sans_Light_Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/HarmonyOS_Sans_Regular.ttf
          weight: 400
        - asset: fonts/HarmonyOS_Sans_Regular_Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/HarmonyOS_Sans_Medium.ttf
          weight: 500
        - asset: fonts/HarmonyOS_Sans_Medium_Italic.ttf
          weight: 500
          style: italic
        - asset: fonts/HarmonyOS_Sans_Bold.ttf
          weight: 700
        - asset: fonts/HarmonyOS_Sans_Bold_Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/HarmonyOS_Sans_Black.ttf
          weight: 900
        - asset: fonts/HarmonyOS_Sans_Black_Italic.ttf
          weight: 900
          style: italic

  assets:
    - assets/images/
